// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { fileURLToPath } from 'url'
import fs from 'fs'
import path from 'path'
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const certPath = path.join(__dirname, 'src/ssl/certificate.pem')
export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // url: `${process.env["AIVEN_DATABASE_SERVICE_URI"]}&sslrootcert=${certPath}`,
    url: process.env["/DATABASE_URL"],
  },
});
